site_name: kmaps

site_url: https://ChangwhaOh.github.io/kmaps

repo_url: https://github.com/ChangwhaOh/kmaps

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"  ### ['filepath/filename.ipynb', ''] to skip running particular files
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/ChangwhaOh/kmaps/issues
    - Examples:
          - FinalExam: examples/10_final_exam.ipynb
          - Introduction: examples/00_introduction.ipynb
          - Folmaps: examples/01_folmaps.ipynb
          - Raster: examples/02_raster.ipynb
          - Image: examples/03_image.ipynb
          - Dropdown: examples/04_dropdown.ipynb
          - Optimization: examples/05_optimization.ipynb
    - API Reference:
          - kmaps module: kmaps.md
          - folmaps module: folmaps.md
